// src/pages/InvoiceCreate.tsx
import { useState, useEffect, useCallback } from 'react'
import { useNavigate, useParams, useLocation } from 'react-router-dom'
import {
  collection, query, where, getDocs, getDoc, addDoc, updateDoc, doc, serverTimestamp
} from 'firebase/firestore'
import { db, auth } from '../firebase'
import type { InvoiceData, InvoiceItem, BillingAddress, BillingSource, ItemMaster } from '../types/invoice'
import { useToast } from '../contexts/ToastContext'

function makeItem(): InvoiceItem {
  return { id: crypto.randomUUID(), description: '', quantity: 1, unitPrice: 0, unit: '', amount: 0 }
}

const oneMonthLater = new Date()
oneMonthLater.setMonth(oneMonthLater.getMonth() + 1)

function initialInvoice(): InvoiceData {
  return {
    invoiceNumber: '',
    invoiceDate: new Date().toISOString().split('T')[0] ?? '',
    dueDate: oneMonthLater.toISOString().split('T')[0] ?? '',
    billingAddressId: undefined,
    clientName: '',
    clientAddress: '',
    clientPhone: '',
    billingSourceId: undefined,
    companyName: '',
    companyAddress: '',
    companyPhone: '',
    companyEmail: '',
    items: [makeItem()],
    subtotal: 0,
    taxRate: 0,
    tax: 0,
    total: 0,
    notes: ''
  }
}

export default function InvoiceCreate() {
  const navigate = useNavigate()
  const { id } = useParams<{ id?: string }>()
  const location = useLocation()
  const { show: showToast } = useToast()

  const isViewMode = location.pathname.startsWith('/view/')
  const isEditMode = location.pathname.startsWith('/edit/')

  const pageTitle = isViewMode ? '請求書詳細' : isEditMode ? '請求書編集' : '請求書作成'

  const [invoice, setInvoice] = useState<InvoiceData>(initialInvoice)
  const [billingAddresses, setBillingAddresses] = useState<BillingAddress[]>([])
  const [billingSources, setBillingSources] = useState<BillingSource[]>([])
  const [itemMasters, setItemMasters] = useState<ItemMaster[]>([])
  const [isGeneratingNumber, setIsGeneratingNumber] = useState(false)

  const selectedBillingAddress = invoice.billingAddressId
    ? billingAddresses.find(a => a.id === invoice.billingAddressId) ?? null
    : null
  const selectedBillingSource = invoice.billingSourceId
    ? billingSources.find(s => s.id === invoice.billingSourceId) ?? null
    : null

  const calcTotals = useCallback((items: InvoiceItem[], taxRate: number) => {
    const subtotal = items.reduce((sum, item) => sum + item.amount, 0)
    const tax = Math.round(subtotal * taxRate / 100)
    return { subtotal, tax, total: subtotal + tax }
  }, [])

  useEffect(() => {
    const uid = auth.currentUser?.uid
    if (!uid) return
    Promise.all([
      getDocs(query(collection(db, 'billingAddresses'), where('uid', '==', uid))),
      getDocs(query(collection(db, 'billingSources'), where('uid', '==', uid))),
      getDocs(query(collection(db, 'itemMasters'), where('uid', '==', uid)))
    ]).then(([addrSnap, srcSnap, itemSnap]) => {
      setBillingAddresses(addrSnap.docs.map(d => ({ id: d.id, ...d.data() } as BillingAddress)))
      setBillingSources(srcSnap.docs.map(d => ({ id: d.id, ...d.data() } as BillingSource)))
      const raw = itemSnap.docs.map(d => ({ id: d.id, ...d.data() } as ItemMaster))
      raw.sort((a, b) => {
        const aO = a.sortOrder ?? Infinity
        const bO = b.sortOrder ?? Infinity
        return aO !== bO ? aO - bO : a.description.localeCompare(b.description, 'ja')
      })
      setItemMasters(raw)
    })
  }, [])

  useEffect(() => {
    if ((isViewMode || isEditMode) && id) {
      getDoc(doc(db, 'invoices', id)).then(snap => {
        if (!snap.exists()) return
        const data = snap.data()
        if (data['uid'] !== auth.currentUser?.uid) {
          alert('アクセス権限がありません')
          navigate('/')
          return
        }
        setInvoice(prev => ({
          ...prev,
          ...data,
          createdAt: data['createdAt']?.toDate?.()?.toISOString() ?? data['createdAt'],
          updatedAt: data['updatedAt']?.toDate?.()?.toISOString() ?? data['updatedAt']
        }) as InvoiceData)
      })
    }
  }, [id, isViewMode, isEditMode, navigate])

  const generateInvoiceNumber = async (billingAddressId: string): Promise<string> => {
    const uid = auth.currentUser?.uid
    if (!uid) return ''
    const address = billingAddresses.find(a => a.id === billingAddressId)
    if (!address?.customerCode) return ''
    const customerCode = address.customerCode
    const now = new Date()
    const yyyymm = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}`
    const prefix = `${customerCode}-${yyyymm}-`
    const snap = await getDocs(query(collection(db, 'invoices'), where('uid', '==', uid), where('billingAddressId', '==', billingAddressId)))
    let maxSeq = 0
    snap.forEach(d => {
      const num = d.data()['invoiceNumber'] as string | undefined
      if (num?.startsWith(prefix)) {
        const seq = parseInt(num.slice(prefix.length), 10)
        if (!isNaN(seq) && seq > maxSeq) maxSeq = seq
      }
    })
    return `${prefix}${String(maxSeq + 1).padStart(3, '0')}`
  }

  const onBillingAddressChange = async (e: React.ChangeEvent<HTMLSelectElement>) => {
    const addrId = e.target.value
    setInvoice(prev => ({ ...prev, billingAddressId: addrId || undefined }))
    if (!addrId) return
    setIsGeneratingNumber(true)
    try {
      const num = await generateInvoiceNumber(addrId)
      setInvoice(prev => ({ ...prev, invoiceNumber: num }))
    } finally {
      setIsGeneratingNumber(false)
    }
  }

  const getItemMasterId = (description: string) => {
    return itemMasters.find(m => m.description === description)?.id ?? ''
  }

  const updateItemAt = (index: number, updates: Partial<InvoiceItem>) => {
    setInvoice(prev => {
      const items = prev.items.map((item, i) => {
        if (i !== index) return item
        const updated = { ...item, ...updates }
        updated.amount = updated.quantity * updated.unitPrice
        return updated
      })
      return { ...prev, items, ...calcTotals(items, prev.taxRate) }
    })
  }

  const onPresetChange = (index: number, masterId: string) => {
    const master = itemMasters.find(m => m.id === masterId)
    if (master) {
      updateItemAt(index, { description: master.description, unitPrice: master.unitPrice, unit: master.unit })
    } else {
      updateItemAt(index, { description: '', unitPrice: 0, unit: '' })
    }
  }

  const addItem = () => {
    setInvoice(prev => {
      const items = [...prev.items, makeItem()]
      return { ...prev, items, ...calcTotals(items, prev.taxRate) }
    })
  }

  const removeItem = (index: number) => {
    setInvoice(prev => {
      if (prev.items.length <= 1) return prev
      const items = prev.items.filter((_, i) => i !== index)
      return { ...prev, items, ...calcTotals(items, prev.taxRate) }
    })
  }

  const saveInvoice = async () => {
    if (!invoice.invoiceNumber) {
      showToast('請求書番号が設定されていません。請求先を選択すると自動採番されます。', 'error')
      return
    }
    if (!invoice.billingAddressId) {
      showToast('請求先を選択してください', 'error')
      return
    }
    if (!invoice.billingSourceId) {
      showToast('請求元を選択してください', 'error')
      return
    }
    const uid = auth.currentUser?.uid
    if (!uid) return
    const clientName = selectedBillingAddress?.name ?? invoice.clientName
    try {
      if (isEditMode && id) {
        await updateDoc(doc(db, 'invoices', id), { ...invoice, clientName, updatedAt: serverTimestamp() })
        showToast('請求書を更新しました')
      } else {
        await addDoc(collection(db, 'invoices'), { ...invoice, clientName, uid, createdAt: serverTimestamp(), updatedAt: serverTimestamp() })
        showToast('請求書を保存しました')
      }
      navigate('/')
    } catch (e) {
      console.error(e)
      showToast('保存中にエラーが発生しました。もう一度お試しください。', 'error')
    }
  }

  return (
    <div className="invoice-form">
      <div className="form-header">
        <button onClick={() => navigate('/')} className="btn-back">← 一覧に戻る</button>
        <h2>{pageTitle}</h2>
        <div className="header-actions">
          {isViewMode && <button onClick={() => navigate(`/print/${id}`)} className="btn-pdf">PDF出力</button>}
          {isViewMode && <button onClick={() => navigate(`/edit/${id}`)} className="btn-edit-header">編集</button>}
          {!isViewMode && <button onClick={saveInvoice} className="btn-save">保存</button>}
        </div>
      </div>

      <div className="form-section">
        <h3>基本情報</h3>
        <div className="form-row">
          <div className="form-group">
            <label>請求書番号</label>
            {!isViewMode ? (
              <div className="invoice-number-field">
                <input
                  type="text"
                  value={invoice.invoiceNumber}
                  onChange={e => setInvoice(prev => ({ ...prev, invoiceNumber: e.target.value }))}
                  placeholder="顧客選択時に自動採番されます"
                  readOnly={isGeneratingNumber}
                  className={isGeneratingNumber ? 'readonly-field' : ''}
                />
                {isGeneratingNumber && <span className="generating-badge">採番中...</span>}
                {!isGeneratingNumber && invoice.invoiceNumber && invoice.billingAddressId && (
                  <span className="auto-generated-badge">自動採番済み</span>
                )}
              </div>
            ) : (
              <input type="text" value={invoice.invoiceNumber} readOnly className="readonly-field" />
            )}
          </div>
          <div className="form-group">
            <label>請求日</label>
            <input
              type="date"
              value={invoice.invoiceDate}
              onChange={e => setInvoice(prev => ({ ...prev, invoiceDate: e.target.value }))}
              readOnly={isViewMode}
              className={isViewMode ? 'readonly-field' : ''}
            />
          </div>
          <div className="form-group">
            <label>支払期限</label>
            <input
              type="date"
              value={invoice.dueDate}
              onChange={e => setInvoice(prev => ({ ...prev, dueDate: e.target.value }))}
              readOnly={isViewMode}
              className={isViewMode ? 'readonly-field' : ''}
            />
          </div>
        </div>
      </div>

      <div className="form-section">
        <h3>請求先情報</h3>
        <div className="form-group">
          <label>お客様名 {!isViewMode && <span className="required">*</span>}</label>
          {!isViewMode ? (
            <select className="form-select" value={invoice.billingAddressId ?? ''} onChange={onBillingAddressChange}>
              <option value="">-- 選択してください --</option>
              {billingAddresses.map(addr => (
                <option key={addr.id} value={addr.id}>
                  {addr.name}{addr.contactPerson ? ` (${addr.contactPerson})` : ''}
                </option>
              ))}
            </select>
          ) : (
            <input type="text" value={selectedBillingAddress?.name ?? invoice.clientName} readOnly className="readonly-field" />
          )}
        </div>
        {selectedBillingAddress && (
          <div className="billing-info-display">
            <div className="info-row"><span className="label">会社名:</span><span className="value">{selectedBillingAddress.name}</span></div>
            {selectedBillingAddress.contactPerson && <div className="info-row"><span className="label">担当者:</span><span className="value">{selectedBillingAddress.contactPerson}</span></div>}
            <div className="info-row"><span className="label">住所:</span><span className="value">{selectedBillingAddress.postalCode ? `〒${selectedBillingAddress.postalCode} ` : ''}{selectedBillingAddress.address}</span></div>
            <div className="info-row"><span className="label">電話番号:</span><span className="value">{selectedBillingAddress.phone}</span></div>
            {selectedBillingAddress.email && <div className="info-row"><span className="label">メールアドレス:</span><span className="value">{selectedBillingAddress.email}</span></div>}
          </div>
        )}
      </div>

      <div className="form-section">
        <h3>請求元情報</h3>
        <div className="form-group">
          <label>会社名 {!isViewMode && <span className="required">*</span>}</label>
          {!isViewMode ? (
            <select className="form-select" value={invoice.billingSourceId ?? ''} onChange={e => setInvoice(prev => ({ ...prev, billingSourceId: e.target.value || undefined }))}>
              <option value="">-- 選択してください --</option>
              {billingSources.map(src => (
                <option key={src.id} value={src.id}>{src.name}</option>
              ))}
            </select>
          ) : (
            <input type="text" value={selectedBillingSource?.name ?? invoice.companyName} readOnly className="readonly-field" />
          )}
        </div>
        {selectedBillingSource && (
          <div className="billing-info-display">
            <div className="info-row"><span className="label">会社名:</span><span className="value">{selectedBillingSource.name}</span></div>
            <div className="info-row"><span className="label">住所:</span><span className="value">{selectedBillingSource.postalCode ? `〒${selectedBillingSource.postalCode} ` : ''}{selectedBillingSource.address}</span></div>
            <div className="info-row"><span className="label">電話番号:</span><span className="value">{selectedBillingSource.phone}</span></div>
            <div className="info-row"><span className="label">メールアドレス:</span><span className="value">{selectedBillingSource.email}</span></div>
            {selectedBillingSource.invoiceRegistrationNumber && <div className="info-row"><span className="label">インボイス登録番号:</span><span className="value">{selectedBillingSource.invoiceRegistrationNumber}</span></div>}
          </div>
        )}
      </div>

      <div className="form-section">
        <h3>明細</h3>
        <div className="items-header">
          <span className="col-desc">品名</span>
          <span className="col-qty">数量</span>
          <span className="col-unit">単位</span>
          <span className="col-price">単価</span>
          <span className="col-amount">金額</span>
          <span className="col-actions"></span>
        </div>
        {invoice.items.map((item, index) => (
          <div key={item.id} className="item-row">
            <div className="item-cell col-desc">
              <span className="item-label">品名</span>
              {!isViewMode ? (
                <select value={getItemMasterId(item.description)} onChange={e => onPresetChange(index, e.target.value)}>
                  <option value="">選択してください</option>
                  {itemMasters.map(m => <option key={m.id} value={m.id}>{m.description}</option>)}
                </select>
              ) : (
                <span className="readonly-value">{item.description || '-'}</span>
              )}
            </div>
            <div className="item-cell col-qty">
              <span className="item-label">数量</span>
              {!isViewMode ? (
                <input
                  type="number"
                  min="0"
                  step="1"
                  value={item.quantity}
                  onChange={e => updateItemAt(index, { quantity: Number(e.target.value) })}
                />
              ) : (
                <span className="readonly-value">{item.quantity}</span>
              )}
            </div>
            <div className="item-cell col-unit">
              <span className="item-label">単位</span>
              <span className="unit-value">{item.unit || '-'}</span>
            </div>
            <div className="item-cell col-price">
              <span className="item-label">単価</span>
              {!isViewMode ? (
                <input
                  type="number"
                  step="1"
                  value={item.unitPrice}
                  onChange={e => updateItemAt(index, { unitPrice: Number(e.target.value) })}
                />
              ) : (
                <span className="readonly-value">￥{item.unitPrice.toLocaleString()}</span>
              )}
            </div>
            <div className="item-cell col-amount">
              <span className="item-label">金額</span>
              <span className="amount-value">￥{item.amount.toLocaleString()}</span>
            </div>
            {!isViewMode ? (
              <button onClick={() => removeItem(index)} className="btn-remove col-actions">削除</button>
            ) : (
              <span className="col-actions"></span>
            )}
          </div>
        ))}
        {!isViewMode && <button onClick={addItem} className="btn-add">+ 明細を追加</button>}
      </div>

      <div className="form-section">
        <h3>金額</h3>
        <div className="form-row">
          <div className="form-group">
            <label>消費税率 (%)</label>
            {!isViewMode ? (
              <input
                type="number"
                min="0"
                max="100"
                step="0.1"
                value={invoice.taxRate}
                onChange={e => {
                  const taxRate = Number(e.target.value)
                  setInvoice(prev => ({ ...prev, taxRate, ...calcTotals(prev.items, taxRate) }))
                }}
              />
            ) : (
              <input type="number" value={invoice.taxRate} readOnly className="readonly-field" />
            )}
          </div>
        </div>
        <div className="totals">
          <div className="total-row"><span>小計:</span><span>￥{invoice.subtotal.toLocaleString()}</span></div>
          <div className="total-row"><span>消費税 ({invoice.taxRate}%):</span><span>￥{invoice.tax.toLocaleString()}</span></div>
          <div className="total-row total-final"><span>合計:</span><span>￥{invoice.total.toLocaleString()}</span></div>
        </div>
      </div>

      <div className="form-section">
        <h3>備考</h3>
        <div className="form-group">
          {!isViewMode ? (
            <textarea
              rows={4}
              placeholder="特記事項があればご記入ください"
              value={invoice.notes}
              onChange={e => setInvoice(prev => ({ ...prev, notes: e.target.value }))}
            />
          ) : (
            <textarea rows={4} value={invoice.notes} readOnly className="readonly-field" />
          )}
        </div>
      </div>

      {!isViewMode && (
        <div className="form-footer">
          <button onClick={saveInvoice} className="btn-save btn-save-footer">保存</button>
        </div>
      )}
    </div>
  )
}

// src/views/InvoiceCreate.vue
<template>
  <div class="invoice-form">
    <div class="form-header">
      <button @click="goBack" class="btn-back">← 一覧に戻る</button>
      <h2>{{ pageTitle }}</h2>
      <div class="header-actions">
        <button v-if="isViewMode" @click="goToPrint" class="btn-pdf">PDF出力</button>
        <button v-if="isViewMode" @click="goToEdit" class="btn-edit-header">編集</button>
        <button v-if="!isViewMode" @click="saveInvoice" class="btn-save">保存</button>
      </div>
    </div>

    <div class="form-section">
      <h3>基本情報</h3>
      <div class="form-row">
        <div class="form-group">
          <label>請求書番号</label>
          <input v-model="invoice.invoiceNumber" type="text" placeholder="INV-001" :readonly="isViewMode" :class="{ 'readonly-field': isViewMode }" />
        </div>
        <div class="form-group">
          <label>請求日</label>
          <input v-model="invoice.invoiceDate" type="date" :readonly="isViewMode" :class="{ 'readonly-field': isViewMode }" />
        </div>
        <div class="form-group">
          <label>支払期限</label>
          <input v-model="invoice.dueDate" type="date" :readonly="isViewMode" :class="{ 'readonly-field': isViewMode }" />
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>請求先情報</h3>
      <div class="form-group">
        <label>お客様名 <span v-if="!isViewMode" class="required">*</span></label>
        <select v-if="!isViewMode" @change="onBillingAddressChange" class="form-select" :value="invoice.billingAddressId">
          <option value="">-- 選択してください --</option>
          <option v-for="address in billingAddresses" :key="address.id" :value="address.id">
            {{ address.name }} {{ address.contactPerson ? `(${address.contactPerson})` : '' }}
          </option>
        </select>
        <input v-else :value="selectedBillingAddress?.name || invoice.clientName" type="text" readonly class="readonly-field" />
      </div>
      <div v-if="selectedBillingAddress" class="billing-info-display">
        <div class="info-row">
          <span class="label">会社名:</span>
          <span class="value">{{ selectedBillingAddress.name }}</span>
        </div>
        <div v-if="selectedBillingAddress.contactPerson" class="info-row">
          <span class="label">担当者:</span>
          <span class="value">{{ selectedBillingAddress.contactPerson }}</span>
        </div>
        <div class="info-row">
          <span class="label">住所:</span>
          <span class="value">{{ selectedBillingAddress.postalCode ? `〒${selectedBillingAddress.postalCode} ` : '' }}{{ selectedBillingAddress.address }}</span>
        </div>
        <div class="info-row">
          <span class="label">電話番号:</span>
          <span class="value">{{ selectedBillingAddress.phone }}</span>
        </div>
        <div v-if="selectedBillingAddress.email" class="info-row">
          <span class="label">メールアドレス:</span>
          <span class="value">{{ selectedBillingAddress.email }}</span>
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>請求元情報</h3>
      <div class="form-group">
        <label>会社名 <span v-if="!isViewMode" class="required">*</span></label>
        <select v-if="!isViewMode" @change="onBillingSourceChange" class="form-select" :value="invoice.billingSourceId">
          <option value="">-- 選択してください --</option>
          <option v-for="source in billingSources" :key="source.id" :value="source.id">
            {{ source.name }}
          </option>
        </select>
        <input v-else :value="selectedBillingSource?.name || invoice.companyName" type="text" readonly class="readonly-field" />
      </div>
      <div v-if="selectedBillingSource" class="billing-info-display">
        <div class="info-row">
          <span class="label">会社名:</span>
          <span class="value">{{ selectedBillingSource.name }}</span>
        </div>
        <div class="info-row">
          <span class="label">住所:</span>
          <span class="value">{{ selectedBillingSource.postalCode ? `〒${selectedBillingSource.postalCode} ` : '' }}{{ selectedBillingSource.address }}</span>
        </div>
        <div class="info-row">
          <span class="label">電話番号:</span>
          <span class="value">{{ selectedBillingSource.phone }}</span>
        </div>
        <div class="info-row">
          <span class="label">メールアドレス:</span>
          <span class="value">{{ selectedBillingSource.email }}</span>
        </div>
        <div v-if="selectedBillingSource.invoiceRegistrationNumber" class="info-row">
          <span class="label">インボイス登録番号:</span>
          <span class="value">{{ selectedBillingSource.invoiceRegistrationNumber }}</span>
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>明細</h3>
      <div class="items-header">
        <span class="col-desc">品名</span>
        <span class="col-qty">数量</span>
        <span class="col-unit">単位</span>
        <span class="col-price">単価</span>
        <span class="col-amount">金額</span>
        <span class="col-actions"></span>
      </div>
      <div v-for="(item, index) in invoice.items" :key="item.id" class="item-row">
        <div class="item-cell col-desc">
          <span class="item-label">品名</span>
          <select
            v-if="!isViewMode"
            :value="getItemMasterId(item.description)"
            @change="onPresetChange(index, ($event.target as HTMLSelectElement).value)"
          >
            <option value="">選択してください</option>
            <option v-for="master in itemMasters" :key="master.id" :value="master.id">
              {{ master.description }}
            </option>
          </select>
          <span v-else class="readonly-value">{{ item.description || '-' }}</span>
        </div>
        <div class="item-cell col-qty">
          <span class="item-label">数量</span>
          <input
            v-if="!isViewMode"
            v-model.number="item.quantity"
            type="number"
            min="0"
            step="1"
            @input="updateItem(index)"
          />
          <span v-else class="readonly-value">{{ item.quantity }}</span>
        </div>
        <div class="item-cell col-unit">
          <span class="item-label">単位</span>
          <span class="unit-value">{{ item.unit || '-' }}</span>
        </div>
        <div class="item-cell col-price">
          <span class="item-label">単価</span>
          <input
            v-if="!isViewMode"
            v-model.number="item.unitPrice"
            type="number"
            step="1"
            @input="updateItem(index)"
          />
          <span v-else class="readonly-value">￥{{ item.unitPrice.toLocaleString() }}</span>
        </div>
        <div class="item-cell col-amount">
          <span class="item-label">金額</span>
          <span class="amount-value">￥{{ item.amount.toLocaleString() }}</span>
        </div>
        <button v-if="!isViewMode" @click="removeItem(index)" class="btn-remove col-actions">削除</button>
        <span v-else class="col-actions"></span>
      </div>
      <button v-if="!isViewMode" @click="addItem" class="btn-add">+ 明細を追加</button>
    </div>

    <div class="form-section">
      <h3>金額</h3>
      <div class="form-row">
        <div class="form-group">
          <label>消費税率 (%)</label>
          <input v-if="!isViewMode" v-model.number="invoice.taxRate" type="number" min="0" max="100" step="0.1" @input="calculateTotals" />
          <input v-else :value="invoice.taxRate" type="number" readonly class="readonly-field" />
        </div>
      </div>
      <div class="totals">
        <div class="total-row">
          <span>小計:</span>
          <span>￥{{ invoice.subtotal.toLocaleString() }}</span>
        </div>
        <div class="total-row">
          <span>消費税 ({{ invoice.taxRate }}%):</span>
          <span>￥{{ invoice.tax.toLocaleString() }}</span>
        </div>
        <div class="total-row total-final">
          <span>合計:</span>
          <span>￥{{ invoice.total.toLocaleString() }}</span>
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>備考</h3>
      <div class="form-group">
        <textarea v-if="!isViewMode" v-model="invoice.notes" rows="4" placeholder="特記事項があればご記入ください"></textarea>
        <textarea v-else :value="invoice.notes" rows="4" readonly class="readonly-field"></textarea>
      </div>
    </div>

    <div v-if="!isViewMode" class="form-footer">
      <button @click="saveInvoice" class="btn-save btn-save-footer">保存</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, onMounted, computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import {
  collection, query, where, getDocs, getDoc, addDoc, updateDoc, doc, serverTimestamp
} from 'firebase/firestore'
import { db, auth } from '../firebase'
import type { InvoiceData, BillingAddress, BillingSource, ItemMaster } from '../types/invoice'

const router = useRouter()
const route = useRoute()
const billingAddresses = ref<BillingAddress[]>([])
const billingSources = ref<BillingSource[]>([])
const itemMasters = ref<ItemMaster[]>([])

const isViewMode = computed(() => route.name === 'invoice-view')
const isEditMode = computed(() => route.name === 'invoice-edit')
const invoiceId = computed(() => route.params.id as string | undefined)

const pageTitle = computed(() => {
  if (isViewMode.value) return '請求書詳細'
  if (isEditMode.value) return '請求書編集'
  return '請求書作成'
})

const oneMonthLater = new Date()
oneMonthLater.setMonth(oneMonthLater.getMonth() + 1)

const invoice = reactive<InvoiceData>({
  invoiceNumber: '',
  invoiceDate: new Date().toISOString().split('T')[0] || '',
  dueDate: oneMonthLater.toISOString().split('T')[0] || '',
  billingAddressId: undefined,
  clientName: '',
  clientAddress: '',
  clientPhone: '',
  billingSourceId: undefined,
  companyName: '',
  companyAddress: '',
  companyPhone: '',
  companyEmail: '',
  items: [
    {
      id: crypto.randomUUID(),
      description: '',
      quantity: 1,
      unitPrice: 0,
      unit: '',
      amount: 0
    }
  ],
  subtotal: 0,
  taxRate: 10,
  tax: 0,
  total: 0,
  notes: ''
})

const loadBillingData = async () => {
  const uid = auth.currentUser?.uid
  if (!uid) return

  const [addrSnap, srcSnap, itemSnap] = await Promise.all([
    getDocs(query(collection(db, 'invoiceBillingAddresses'), where('uid', '==', uid))),
    getDocs(query(collection(db, 'invoiceBillingSources'), where('uid', '==', uid))),
    getDocs(query(collection(db, 'invoiceItemMasters'), where('uid', '==', uid)))
  ])

  billingAddresses.value = addrSnap.docs.map(d => ({ id: d.id, ...d.data() } as BillingAddress))
  billingSources.value = srcSnap.docs.map(d => ({ id: d.id, ...d.data() } as BillingSource))
  itemMasters.value = itemSnap.docs.map(d => ({ id: d.id, ...d.data() } as ItemMaster))
}

const selectedBillingAddress = computed(() =>
  invoice.billingAddressId ? billingAddresses.value.find(a => a.id === invoice.billingAddressId) : null
)

const selectedBillingSource = computed(() =>
  invoice.billingSourceId ? billingSources.value.find(s => s.id === invoice.billingSourceId) : null
)

const onBillingAddressChange = (e: Event) => {
  invoice.billingAddressId = (e.target as HTMLSelectElement).value
}

const onBillingSourceChange = (e: Event) => {
  invoice.billingSourceId = (e.target as HTMLSelectElement).value
}

const addItem = () => {
  invoice.items.push({
    id: crypto.randomUUID(),
    description: '',
    quantity: 1,
    unitPrice: 0,
    unit: '',
    amount: 0
  })
}

const getItemMasterId = (description: string): string => {
  const master = itemMasters.value.find(m => m.description === description)
  return master ? master.id : ''
}

const onPresetChange = (index: number, itemMasterId: string) => {
  const item = invoice.items[index]
  if (!item) return
  const master = itemMasters.value.find(m => m.id === itemMasterId)
  if (master) {
    item.description = master.description
    item.unitPrice = master.unitPrice
    item.unit = master.unit
  } else {
    item.description = ''
    item.unitPrice = 0
    item.unit = ''
  }
  updateItem(index)
}

const removeItem = (index: number) => {
  if (invoice.items.length > 1) {
    invoice.items.splice(index, 1)
    calculateTotals()
  }
}

const updateItem = (index: number) => {
  const item = invoice.items[index]
  if (item) {
    item.amount = item.quantity * item.unitPrice
    calculateTotals()
  }
}

const calculateTotals = () => {
  invoice.subtotal = invoice.items.reduce((sum, item) => sum + item.amount, 0)
  invoice.tax = Math.round(invoice.subtotal * invoice.taxRate / 100)
  invoice.total = invoice.subtotal + invoice.tax
}

calculateTotals()

const loadInvoice = async (id: string) => {
  const docSnap = await getDoc(doc(db, 'invoiceInvoices', id))
  if (!docSnap.exists()) return
  const data = docSnap.data()
  if (data.uid !== auth.currentUser?.uid) {
    alert('アクセス権限がありません')
    router.push('/')
    return
  }
  Object.assign(invoice, {
    ...data,
    createdAt: data.createdAt?.toDate?.()?.toISOString() ?? data.createdAt,
    updatedAt: data.updatedAt?.toDate?.()?.toISOString() ?? data.updatedAt
  })
}

onMounted(async () => {
  await loadBillingData()
  if ((isViewMode.value || isEditMode.value) && invoiceId.value) {
    await loadInvoice(invoiceId.value)
  }
})

const goBack = () => router.push('/')
const goToEdit = () => router.push(`/edit/${invoiceId.value}`)
const goToPrint = () => router.push(`/print/${invoiceId.value}`)

const saveInvoice = async () => {
  if (!invoice.invoiceNumber) {
    alert('請求書番号を入力してください')
    return
  }
  if (!invoice.billingAddressId) {
    alert('請求先を選択してください')
    return
  }
  if (!invoice.billingSourceId) {
    alert('請求元を選択してください')
    return
  }

  const uid = auth.currentUser?.uid
  if (!uid) return

  const clientName = selectedBillingAddress.value?.name ?? invoice.clientName

  if (isEditMode.value && invoiceId.value) {
    await updateDoc(doc(db, 'invoiceInvoices', invoiceId.value), {
      ...invoice,
      clientName,
      updatedAt: serverTimestamp()
    })
    alert('請求書を更新しました')
  } else {
    await addDoc(collection(db, 'invoiceInvoices'), {
      ...invoice,
      clientName,
      uid,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp()
    })
    alert('請求書を保存しました')
  }

  router.push('/')
}
</script>

<style scoped>
.invoice-form {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
}

.invoice-form * {
  box-sizing: border-box;
}

.form-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 30px;
  padding: 20px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.form-header h2 {
  margin: 0;
  color: #2c3e50;
}

.btn-back {
  padding: 10px 20px;
  background: #95a5a6;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  transition: background 0.3s;
}

.btn-back:hover {
  background: #7f8c8d;
}

.btn-edit-header {
  padding: 10px 24px;
  background: #f39c12;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
  font-weight: 600;
  transition: background 0.3s;
}

.btn-edit-header:hover {
  background: #e67e22;
}

.btn-pdf {
  padding: 10px 24px;
  background: #2980b9;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
  font-weight: 600;
  transition: background 0.3s;
}

.btn-pdf:hover {
  background: #2471a3;
}

.readonly-field {
  background: #f8f9fa !important;
  color: #555;
  cursor: default;
}

.readonly-value {
  display: block;
  padding: 8px;
  background: #f8f9fa;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
  color: #2c3e50;
}

.header-actions {
  display: flex;
  gap: 10px;
}

.btn-save {
  padding: 10px 24px;
  background: #27ae60;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
  font-weight: 600;
  transition: background 0.3s;
}

.btn-save:hover {
  background: #229954;
}

h2 {
  color: #2c3e50;
  margin-bottom: 30px;
}

.form-section {
  background: white;
  padding: 20px;
  margin-bottom: 20px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

h3 {
  color: #34495e;
  margin-top: 0;
  margin-bottom: 20px;
  padding-bottom: 10px;
  border-bottom: 2px solid #3498db;
}

.form-row {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 15px;
  margin-bottom: 15px;
}

.form-group {
  margin-bottom: 15px;
}

.form-group label {
  display: block;
  margin-bottom: 5px;
  color: #555;
  font-weight: 500;
}

.form-group input,
.form-group textarea,
.form-select {
  width: 100%;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
  box-sizing: border-box;
}

.form-group input:focus,
.form-group textarea:focus,
.form-select:focus {
  outline: none;
  border-color: #3498db;
}

.form-select {
  background-color: white;
  cursor: pointer;
}

.required {
  color: #e74c3c;
  margin-left: 4px;
}

.billing-info-display {
  background: #f8f9fa;
  border: 1px solid #ddd;
  border-radius: 4px;
  padding: 15px;
  margin-top: 10px;
}

.info-row {
  display: flex;
  padding: 8px 0;
  border-bottom: 1px solid #e9ecef;
}

.info-row:last-child {
  border-bottom: none;
}

.info-row .label {
  font-weight: 500;
  color: #555;
  min-width: 120px;
  flex-shrink: 0;
}

.info-row .value {
  color: #2c3e50;
  word-break: break-word;
}

.items-header {
  display: grid;
  grid-template-columns: 2fr 1fr 0.7fr 1fr 1fr 100px;
  gap: 10px;
  padding: 10px;
  background: #f8f9fa;
  border-radius: 4px;
  font-weight: 600;
  margin-bottom: 10px;
}

.item-row {
  display: grid;
  grid-template-columns: 2fr 1fr 0.7fr 1fr 1fr 100px;
  gap: 10px;
  padding: 10px;
  margin-bottom: 10px;
  align-items: center;
  background: #fff;
  border: 1px solid #e9ecef;
  border-radius: 4px;
}

.item-cell {
  min-width: 0;
}

.item-cell input,
.item-cell select {
  width: 100%;
  padding: 8px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
  background: white;
}

.item-label {
  display: none;
  font-size: 12px;
  font-weight: 600;
  color: #555;
  margin-bottom: 4px;
}

.col-desc { min-width: 0; }
.col-qty { text-align: center; }
.col-qty input { text-align: center; }
.col-unit { text-align: center; color: #555; }
.col-unit .unit-value { display: block; }
.col-price { text-align: right; }
.col-price input { text-align: right; }
.col-amount {
  text-align: right;
  font-weight: 600;
  padding-right: 10px;
  min-width: 0;
  word-break: break-word;
}

.col-amount .amount-value {
  display: block;
}

.btn-remove {
  padding: 6px 12px;
  background: #e74c3c;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 12px;
  width: 100%;
}

.btn-remove:hover {
  background: #c0392b;
}

.btn-add {
  margin-top: 10px;
  padding: 10px 20px;
  background: #27ae60;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
}

.btn-add:hover {
  background: #229954;
}

.totals {
  margin-top: 20px;
  padding: 20px;
  background: #f8f9fa;
  border-radius: 4px;
}

.total-row {
  display: flex;
  justify-content: space-between;
  padding: 10px 0;
  font-size: 16px;
}

.total-final {
  font-size: 20px;
  font-weight: 700;
  color: #2c3e50;
  border-top: 2px solid #3498db;
  margin-top: 10px;
  padding-top: 15px;
}

.form-footer {
  display: flex;
  justify-content: flex-end;
  margin-top: 10px;
  margin-bottom: 30px;
}

.btn-save-footer {
  padding: 14px 40px;
  font-size: 16px;
}

@media (max-width: 768px) {
  .invoice-form {
    padding: 12px;
  }

  .form-header {
    flex-direction: column;
    gap: 12px;
    align-items: stretch;
    padding: 16px;
  }

  .form-header h2 {
    text-align: center;
    font-size: 20px;
  }

  .btn-back {
    width: 100%;
    padding: 12px;
  }

  .header-actions {
    justify-content: stretch;
  }

  .btn-save {
    width: 100%;
    padding: 12px;
  }

  .form-footer {
    justify-content: stretch;
  }

  .btn-save-footer {
    width: 100%;
  }

  .form-section {
    padding: 16px;
  }

  .form-group input,
  .form-group textarea,
  .item-cell input,
  .item-cell select {
    font-size: 16px;
  }

  .form-row {
    grid-template-columns: 1fr;
    gap: 12px;
  }

  .items-header {
    display: none;
  }

  .item-row {
    grid-template-columns: 1fr;
    gap: 12px;
    padding: 14px;
  }

  .item-label {
    display: block;
  }

  .col-qty,
  .col-unit,
  .col-price,
  .col-amount {
    text-align: left;
    padding-right: 0;
  }

  .col-qty input,
  .col-price input {
    text-align: left;
  }

  .btn-remove {
    margin-top: 4px;
    padding: 10px;
    font-size: 14px;
  }

  .btn-add {
    width: 100%;
  }

  .total-row {
    font-size: 15px;
  }

  .total-final {
    font-size: 18px;
  }
}

@media (max-width: 480px) {
  .invoice-form {
    padding: 8px;
  }

  .form-header,
  .form-section {
    padding: 14px;
  }

  h3 {
    font-size: 16px;
  }
}
</style>
