// src/views/BillingAddressForm.vue
<template>
  <div class="address-form">
    <div class="form-header">
      <button @click="goBack" class="btn-back">← 一覧に戻る</button>
      <h2>{{ isEdit ? '請求先を編集' : '請求先を追加' }}</h2>
      <div class="header-actions">
        <button @click="saveAddress" class="btn-save">保存</button>
      </div>
    </div>

    <div class="form-section">
      <h3>請求先情報</h3>
      <div v-if="isEdit" class="form-group">
        <label>顧客コード</label>
        <input :value="address.customerCode" type="text" disabled class="input-readonly" />
      </div>
      <div v-else class="form-group customer-code-preview">
        <label>顧客コード</label>
        <span class="code-auto-badge">保存時に自動採番されます</span>
      </div>
      <div class="form-group">
        <label>請求先名 <span class="required">*</span></label>
        <input v-model="address.name" type="text" placeholder="株式会社〇〇" />
      </div>
      <div class="form-group">
        <label>担当者名</label>
        <input v-model="address.contactPerson" type="text" placeholder="山田 太郎" />
      </div>
      <div class="form-row">
        <div class="form-group">
          <label>郵便番号</label>
          <input v-model="address.postalCode" type="text" placeholder="123-4567" />
        </div>
      </div>
      <div class="form-group">
        <label>住所</label>
        <input v-model="address.address" type="text" placeholder="東京都〇〇区..." />
      </div>
      <div class="form-row">
        <div class="form-group">
          <label>電話番号</label>
          <input v-model="address.phone" type="tel" placeholder="03-1234-5678" />
        </div>
        <div class="form-group">
          <label>メールアドレス</label>
          <input v-model="address.email" type="email" placeholder="info@example.com" />
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>備考</h3>
      <div class="form-group">
        <textarea v-model="address.notes" rows="4" placeholder="特記事項があればご記入ください"></textarea>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { doc, getDoc, addDoc, updateDoc, collection, serverTimestamp, runTransaction } from 'firebase/firestore'
import { db, auth } from '../firebase'
import { authReady } from '../router'
import type { BillingAddress } from '../types/invoice'
import { useToast } from '../composables/useToast'

const { show: showToast } = useToast()

const route = useRoute()
const router = useRouter()

const editId = computed(() => {
  const id = route.params.id
  return typeof id === 'string' ? id : ''
})

const isEdit = computed(() => editId.value !== '')

const address = reactive<Omit<BillingAddress, 'id' | 'createdAt' | 'updatedAt'>>({
  customerCode: '',
  name: '',
  contactPerson: '',
  postalCode: '',
  address: '',
  phone: '',
  email: '',
  notes: ''
})

const loadForEdit = async () => {
  await authReady
  const docRef = doc(db, 'billingAddresses', editId.value)
  const docSnap = await getDoc(docRef)
  if (!docSnap.exists()) {
    alert('指定された請求先が見つかりません')
    router.push('/billing-addresses')
    return
  }
  const data = docSnap.data()
  if (data.uid !== auth.currentUser?.uid) {
    alert('アクセス権限がありません')
    router.push('/billing-addresses')
    return
  }
  Object.assign(address, {
    customerCode: data.customerCode ?? '',
    name: data.name ?? '',
    contactPerson: data.contactPerson ?? '',
    postalCode: data.postalCode ?? '',
    address: data.address ?? '',
    phone: data.phone ?? '',
    email: data.email ?? '',
    notes: data.notes ?? ''
  })
}

const generateCustomerCode = async (uid: string): Promise<string> => {
  const counterRef = doc(db, 'counters', `customerCode_${uid}`)
  const nextNumber = await runTransaction(db, async (transaction) => {
    const counterSnap = await transaction.get(counterRef)
    const current = counterSnap.exists() ? (counterSnap.data().value as number) : 0
    const next = current + 1
    transaction.set(counterRef, { value: next })
    return next
  })
  return `C${String(nextNumber).padStart(5, '0')}`
}

const goBack = () => router.push('/billing-addresses')

const saveAddress = async () => {
  if (!address.name.trim()) {
    showToast('請求先名を入力してください', 'error')
    return
  }

  const uid = auth.currentUser?.uid
  if (!uid) return

  try {
    if (isEdit.value) {
      await updateDoc(doc(db, 'billingAddresses', editId.value), {
        ...address,
        updatedAt: serverTimestamp()
      })
      showToast('請求先を更新しました')
    } else {
      const customerCode = await generateCustomerCode(uid)
      await addDoc(collection(db, 'billingAddresses'), {
        ...address,
        customerCode,
        uid,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      })
      showToast('請求先を追加しました')
    }
    router.push('/billing-addresses')
  } catch (e) {
    console.error(e)
    showToast('保存中にエラーが発生しました。もう一度お試しください。', 'error')
  }
}

onMounted(() => {
  if (isEdit.value) loadForEdit()
})
</script>

<style scoped>
.address-form {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
}

.address-form * {
  box-sizing: border-box;
}

.form-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 30px;
  padding: 20px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.form-header h2 {
  margin: 0;
  color: #2c3e50;
}

.btn-back {
  padding: 10px 20px;
  background: #95a5a6;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  transition: background 0.3s;
}

.btn-back:hover {
  background: #7f8c8d;
}

.header-actions {
  display: flex;
  gap: 10px;
}

.btn-save {
  padding: 10px 24px;
  background: #27ae60;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
  font-weight: 600;
  transition: background 0.3s;
}

.btn-save:hover {
  background: #229954;
}

.form-section {
  background: white;
  padding: 20px;
  margin-bottom: 20px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

h3 {
  color: #34495e;
  margin-top: 0;
  margin-bottom: 20px;
  padding-bottom: 10px;
  border-bottom: 2px solid #3498db;
}

.form-row {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 15px;
  margin-bottom: 15px;
}

.form-group {
  margin-bottom: 15px;
}

.form-group label {
  display: block;
  margin-bottom: 5px;
  color: #555;
  font-weight: 500;
}

.required {
  color: #e74c3c;
  margin-left: 4px;
}

.form-group input,
.form-group textarea {
  width: 100%;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
  box-sizing: border-box;
}

.form-group input:focus,
.form-group textarea:focus {
  outline: none;
  border-color: #3498db;
}

.input-readonly {
  background: #f4f6f8;
  color: #666;
  cursor: default;
}

.customer-code-preview {
  display: flex;
  align-items: center;
  gap: 12px;
}

.customer-code-preview label {
  margin-bottom: 0;
  white-space: nowrap;
}

.code-auto-badge {
  display: inline-block;
  padding: 4px 10px;
  background: #eaf4fb;
  color: #2980b9;
  border: 1px solid #aed6f1;
  border-radius: 4px;
  font-size: 13px;
}

@media (max-width: 768px) {
  .address-form {
    padding: 12px;
  }

  .form-header {
    flex-direction: column;
    gap: 12px;
    align-items: stretch;
    padding: 16px;
  }

  .form-header h2 {
    text-align: center;
    font-size: 20px;
  }

  .btn-back {
    width: 100%;
    padding: 12px;
  }

  .header-actions {
    justify-content: stretch;
  }

  .btn-save {
    width: 100%;
    padding: 12px;
  }

  .form-section {
    padding: 16px;
  }

  .form-group input,
  .form-group textarea {
    font-size: 16px;
  }

  .form-row {
    grid-template-columns: 1fr;
    gap: 12px;
  }
}

@media (max-width: 480px) {
  .address-form {
    padding: 8px;
  }

  .form-header,
  .form-section {
    padding: 14px;
  }

  h3 {
    font-size: 16px;
  }
}
</style>

// src/pages/BillingAddressForm.tsx
import { useState, useEffect } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { doc, getDoc, addDoc, updateDoc, getDocs, collection, query, where, serverTimestamp } from 'firebase/firestore'
import { db, auth } from '../firebase'
import { useToast } from '../contexts/ToastContext'

interface FormData {
  customerCode: string
  name: string
  contactPerson: string
  postalCode: string
  address: string
  phone: string
  email: string
  notes: string
}

export default function BillingAddressForm() {
  const navigate = useNavigate()
  const { id } = useParams<{ id?: string }>()
  const { show: showToast } = useToast()
  const isEdit = !!id

  const [form, setForm] = useState<FormData>({
    customerCode: '', name: '', contactPerson: '', postalCode: '',
    address: '', phone: '', email: '', notes: ''
  })

  useEffect(() => {
    if (!isEdit || !id) return
    const load = async () => {
      const docSnap = await getDoc(doc(db, 'billingAddresses', id))
      if (!docSnap.exists()) {
        alert('指定された請求先が見つかりません')
        navigate('/billing-addresses')
        return
      }
      const data = docSnap.data()
      if (data['uid'] !== auth.currentUser?.uid) {
        alert('アクセス権限がありません')
        navigate('/billing-addresses')
        return
      }
      setForm({
        customerCode: data['customerCode'] ?? '',
        name: data['name'] ?? '',
        contactPerson: data['contactPerson'] ?? '',
        postalCode: data['postalCode'] ?? '',
        address: data['address'] ?? '',
        phone: data['phone'] ?? '',
        email: data['email'] ?? '',
        notes: data['notes'] ?? ''
      })
    }
    load()
  }, [id, isEdit, navigate])

  const generateCustomerCode = async (uid: string): Promise<string> => {
    const snap = await getDocs(query(collection(db, 'billingAddresses'), where('uid', '==', uid)))
    let maxNum = 0
    snap.forEach(d => {
      const code = d.data()['customerCode'] as string | undefined
      if (code && /^C\d+$/.test(code)) {
        const n = parseInt(code.slice(1), 10)
        if (n > maxNum) maxNum = n
      }
    })
    return `C${String(maxNum + 1).padStart(5, '0')}`
  }

  const handleSave = async () => {
    if (!form.name.trim()) {
      showToast('請求先名を入力してください', 'error')
      return
    }
    const uid = auth.currentUser?.uid
    if (!uid) return
    try {
      if (isEdit && id) {
        await updateDoc(doc(db, 'billingAddresses', id), { ...form, updatedAt: serverTimestamp() })
        showToast('請求先を更新しました')
      } else {
        const customerCode = await generateCustomerCode(uid)
        await addDoc(collection(db, 'billingAddresses'), { ...form, customerCode, uid, createdAt: serverTimestamp(), updatedAt: serverTimestamp() })
        showToast('請求先を追加しました')
      }
      navigate('/billing-addresses')
    } catch (e) {
      console.error(e)
      showToast('保存中にエラーが発生しました。もう一度お試しください。', 'error')
    }
  }

  const set = (field: keyof FormData) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) =>
    setForm(prev => ({ ...prev, [field]: e.target.value }))

  return (
    <div className="address-form">
      <div className="form-header">
        <button onClick={() => navigate('/billing-addresses')} className="btn-back">← 一覧に戻る</button>
        <h2>{isEdit ? '請求先を編集' : '請求先を追加'}</h2>
        <div className="header-actions">
          <button onClick={handleSave} className="btn-save">保存</button>
        </div>
      </div>

      <div className="form-section">
        <h3>請求先情報</h3>
        {isEdit ? (
          <div className="form-group">
            <label>顧客コード</label>
            <input value={form.customerCode} type="text" disabled className="input-readonly" />
          </div>
        ) : (
          <div className="form-group customer-code-preview">
            <label>顧客コード</label>
            <span className="code-auto-badge">保存時に自動採番されます</span>
          </div>
        )}
        <div className="form-group">
          <label>請求先名 <span className="required">*</span></label>
          <input value={form.name} onChange={set('name')} type="text" placeholder="株式会社〇〇" />
        </div>
        <div className="form-group">
          <label>担当者名</label>
          <input value={form.contactPerson} onChange={set('contactPerson')} type="text" placeholder="山田 太郎" />
        </div>
        <div className="form-row">
          <div className="form-group">
            <label>郵便番号</label>
            <input value={form.postalCode} onChange={set('postalCode')} type="text" placeholder="123-4567" />
          </div>
        </div>
        <div className="form-group">
          <label>住所</label>
          <input value={form.address} onChange={set('address')} type="text" placeholder="東京都〇〇区..." />
        </div>
        <div className="form-row">
          <div className="form-group">
            <label>電話番号</label>
            <input value={form.phone} onChange={set('phone')} type="tel" placeholder="03-1234-5678" />
          </div>
          <div className="form-group">
            <label>メールアドレス</label>
            <input value={form.email} onChange={set('email')} type="email" placeholder="info@example.com" />
          </div>
        </div>
      </div>

      <div className="form-section">
        <h3>備考</h3>
        <div className="form-group">
          <textarea value={form.notes} onChange={set('notes')} rows={4} placeholder="特記事項があればご記入ください" />
        </div>
      </div>
    </div>
  )
}
